version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 3002:3002
    depends_on:
      - mariadb2
      - keycloak
    environment:
      - NODE_ENV=production
      - DB_HOST=db-loadbalancer
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_DATABASE=posts
      - KEYCLOAK_URL=http://keycloak:8080/realms/myrealm
      - KEYCLOAK_REALM=myrealm

  frontend:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
      - keycloak
    environment:
      - REACT_APP_KEYCLOAK_URL=http://keycloak:8080/realms/myrealm
      - REACT_APP_KEYCLOAK_REALM=myrealm
      - REACT_APP_CLIENT_ID=myclient
      - REACT_APP_USERNAME=user
      - REACT_APP_PASSWORD=password
  
  frontend-dev:
    build: ./frontend-dev
    ports:
      - 3005:3005
    depends_on:
      - backend
      - keycloak
    environment:
      - REACT_APP_KEYCLOAK_URL=http://keycloak:8080/realms/myrealm
      - REACT_APP_KEYCLOAK_REALM=myrealm
      - REACT_APP_CLIENT_ID=myclient
      - REACT_APP_USERNAME=user
      - REACT_APP_PASSWORD=password

  mariadb1:
    image: mariadb:10.5
    container_name: mariadb1
    ports:
      - "3307:3306"
    environment:
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=posts
      - MARIADB_ROOT_PASSWORD=admin
    volumes:
      - ./mariadb1/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
    cap_add:
      - all
    networks:
      - mariadb

  mariadb2:
    image: mariadb:10.5
    container_name: mariadb2
    ports:
      - "3308:3306"
    environment:
      - MARIADB_PASSWORD=admin
      - MARIADB_DATABASE=posts
      - MARIADB_ROOT_PASSWORD=admin
    volumes:
      - ./mariadb2/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf
    cap_add:
      - all
    networks:
      - mariadb
    depends_on:
      - mariadb1
  
  db-loadbalancer:
    image: mariadb/maxscale:24.02.1
    ports:
      - "3306:3306"
      - "8989:8989"
    depends_on:
      - mariadb1
      - mariadb2
    networks:
      - mariadb

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    command: start-dev --import-realm

volumes:
  db_data:

networks:
  mariadb:
    driver: bridge

